### ISSUE TITLE
Raceband 2 +3 not saved

### ISSUE THREAD

**Issue by derdanu** [betaflight/betaflight-tx-lua-scripts#113]
Setup:
Furious FPV Fortini OSD (BF 3.2.4
Furious FPV Stealth (improved Version / new connector) 
Frsky X9D + opentx 2.2.0
Lua 1.0.1 

Changing VTX channels works fine, but only Raceband 2 and 3 were not saved. The Script tries to retry the process but fails again. 

Any way to provide a debug log? 

Transmitter and LUA combination works well on other Setups.

**Comment by derdanu** [comment]
Similar like #112 as it uses the protocol, but I run R-XSR as well. BTW tested all firmwares provided by Frsky.  The other working Setups don't have an R-XSR receiver.

**Comment by codecae** [comment]
If you're having issues with the r-xsr, please try using a more recent build of 3.3 from ci.betaflight.tech

**Comment by derdanu** [comment]
Same issue with 3.3 Build #583 https://ci.betaflight.tech/job/Betaflight/583/

**Comment by codecae** [comment]
I unfortunately do not have a tramp-based VTX so I have no way of reproducing this issue.  Hopefully someone else has one and can chime in.

**Comment by derdanu** [comment]
@codecae please drop a line at Tech@furiousfpv.com and ask for Tommy Schintgen.  Please provide my name in the conversation as I talked with him. Maybe he can send you a Stealth VTX for testing and further development.

**Comment by Sybalau** [comment]
I have the same isue with Stealth Race VTX. Raceband 2 and 3 don't saved.

**Comment by codecae** [comment]
@derdanu Thank you for the follow-up!  I will reach out now.

**Comment by codecae** [comment]
@derdanu I have written an email to the suggested email and am awaiting a response.  Thanks for your help!

**Comment by eumelOne** [comment]
I also have observed this issue with a unify pro hv race edition. Only RB2 and RB3 won't be saved...

**Comment by derdanu** [comment]
@eumelOne I can confirm this. A mate has the same issue with an unify nano.
It defintily a R-XSR bug. I have switched on of these Setups to a crossfire nano RX. Saving Channel 3 works like a charm.

**Comment by Brisingrox** [comment]
I have tested this issue with FortiniF4/FortiniF4osd rev1+rev2 but with the SPD15 Receiver and didn't encounter any issues.
Tested with Steahlt Race and Long Range without issues

**Comment by gregory-gauthier** [comment]
same issue, can't save Raceband 2 & 3

**Comment by gregory-gauthier** [comment]
Same issue, I can't save Raceband 2 & 3
VTX : Unify Pro HV Race
RX : R-XSR (firmware 171103)
FC : LUX V2 & Micro Lux V2 (Betaflight 3.2.5)

**Comment by ps915** [comment]
Same for me.

KISS FC V2 
ImmersionRC Tramp

I could change channels to RB3. I replaced it with a TBS Unify and i worked!

**Comment by dbertschi** [comment]
Same issue for me.
Fortini F4, RSXR 171103, Furious Stealth VTX. BF 3.3.0.
On the OSD i can change to all RaceBand channels - but vith the latest LUA Script on my X7, RB2 and RB3 can't be saved.

**Comment by Barux** [comment]
Same here running BF 3.2.0, OpenTX 2.2.1, latest lua V1.01, R-xsr, Stealth race.
Can save with BT app and via Pidflight vtx

Any solutions?

**Comment by David-VG** [comment]
Just while solved, try FPORT.

https://github.com/betaflight/betaflight/wiki/The-FrSky-FPort-Protocol

**Comment by DaEmpty** [comment]
Same for me
Kiss FC V1 BF3.3.1
R-XSR (tried all versions)
Unify Race

With the normal XSR everythings works fine

**Comment by Barux** [comment]
Yes guys, FPORS solved all lua script problems I had

Il giorno mer 18 apr 2018 alle ore 20:22 gregory-gauthier <
notifications@github.com> ha scritto:

**Comment by rustbg** [comment]
Same here. R-XSR, BF 3.4 stable. R2 and R3 are not saved. 
Using latest lua script with the dsetpoint fixed. 
Tried so far:
R-XSR on LBT and FCC
F-Port (un-inverted)
Un-inverted s.port + inverted sbus
Inverted s.port on softserial + inverted sbus

**Comment by Cookiedealer** [comment]
Thank you very mich for all Information!
Hello fro.e North Germany
FlipFlopRacer
Am 18.07.18, 08:31, rustbg <notifications@github.com> schrieb:
Same here. R-XSR, BF 3.4 stable. R2 and R3 are not saved.
Using latest lua script with the dsetpoint fixed.
Tried so far:
R-XSR on LBT and FCC
F-Port (un-inverted)
Un-inverted s.port + inverted sbus
Inverted s.port on softserial + inverted sbus

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/betaflight/betaflight-tx-lua-scripts","title":"betaflight/betaflight-tx-lua-scripts","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/betaflight/betaflight-tx-lua-scripts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rustbg in #113: Same here. R-XSR, BF 3.4 stable. R2 and R3 are not saved. \r\nUsing latest lua script with the dsetpoint fixed. \r\nTried so far:\r\nR-XSR on LBT and FCC\r\nF-Port (un-inverted)\r\nUn-inverted s.port + inverted sbus\r\nInverted s.port on softserial + inverted sbus"}],"action":{"name":"View Issue","url":"https://github.com/betaflight/betaflight-tx-lua-scripts/issues/113#issuecomment-405824028"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/betaflight/betaflight-tx-lua-scripts/issues/113#issuecomment-405824028",
"url": "https://github.com/betaflight/betaflight-tx-lua-scripts/issues/113#issuecomment-405824028",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [betaflight/betaflight-tx-lua-scripts] Raceband 2 +3 not saved (#113)",
"sections": [
{
"text": "",
"activityTitle": "**rustbg**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@rustbg",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"betaflight/betaflight-tx-lua-scripts\",\n\"issueId\": 113,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/betaflight/betaflight-tx-lua-scripts/issues/113#issuecomment-405824028"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 301328895\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by David-VG** [comment]
@rustbg I dont have this issue with FPORT, are you sure you have?

**Comment by rustbg** [comment]
Fport was even worse for me, as PID page was completely not functional :-(
Best result is uninverted (hacked) s.port, where just r2/3 don't work, but everything else is ok, even some say retrying, but eventually do save after a bit more time.

**Comment by Benaresq** [comment]
I just semi-resolved this issue by changing to Fport. The channels save now, but the script always says "Retrying" after each channel change.

**Comment by DaEmpty** [comment]
FPort requires a bidirectional inverter on your fc. if you have e.g. an omnibus f4, you are lost. Smartport does not support vtx channel 2+3, and FPort is not working when you want to use the plug of the r-xsr. And even if you solder a cable to the uninverted signal pad, you get retrying messages all the time.

Ignoring such a major bug for almost a year now, is a clear statement from the betaflight development team. The OSD works fine, it's just not very convenient for changing vtx channels. But at least it does it's job.

**Comment by mikeller** [comment]
@DaEmpty: Why don't you submit a fix for the bug that you think there is, instead of just making accusations of bugs being 'ignored'?

**Comment by Benaresq** [comment]
@DaEmpty I've got telemetry working and the LUA scripts all appear to be fine, I'm running a custom script to change channel from a switch that seems to work OK.

When I was running Sport, if I had the Channel LUA page open, it would update when I hit my channel change switch, but now I have to select update to see that it's changed. On the plus side, Raceband 2 and 3 work now, so it solved the problem I was having.
