### ISSUE TITLE
[Feature] Add 50mW for Unify Pro Nano

### ISSUE THREAD

**Issue by mhfpv** [betaflight/betaflight-tx-lua-scripts#141]
It will be nice if  I can set the 50mW option on my TBS Unify Nano via TX. 
Can somebody add in the drop down menu another value to set the 50mW option?

Another question and in my opinion a cool feature:
Is it possible to add instead off the smart Audio feature in Betaflight a special Smart Audio which contains the specs of each VTX. 
For example: If you select "Smart Audio Unify Pro HV Race" in Betaflight you only can set the power output to 25 or 200mW in the BF script on your transmitter. If you select "Smart Audio Unify Pro Nano" you only can set the power output to 25 or 50mW. 

Looking forward to get some feedback if it is possible. Thanks!

**Comment by codecae** [comment]
There is no way to distinguish which VTX type/model you are using.  The values are changed using an index value (0-n) where 0 is the lowest value and n is the highest value.  Since the 50mw setting is the second of two different options, the traditional 200mw setting on the lua script should use the 50mw output level.
