### ISSUE TITLE
vtx values get overwritten at power up

### ISSUE THREAD

**Issue by janbolt** [betaflight/betaflight-tx-lua-scripts#180]
the default values (Band F, Channel 2, 25mW) are send to the vtx at each power up.
Once changed, I would like my values to be stored.

**Comment by RipperDrone** [comment]
did you save them or just change?

**Comment by bobbfwed** [comment]
> Once changed, I would like my values to be stored.
Are you changing them using the Lua script (or OSD)? Or by pressing the button on the VTX?

**Comment by RipperDrone** [comment]
Lua. Just wanted to make sure you set the values, then long-press menu and 'save'. OTherwise you just leave the page and values are NOT stored. Each individual Lua page needs to be saved separately...

In some cases, I have found deleting the vtx channel, freq, ... settings via CLI helped to retain Lua script values...

**Comment by janbolt** [comment]
I have changed the values via lua script and saved them.
