### ISSUE TITLE
pit mode not working

### ISSUE THREAD

**Issue by bonoboxita** [betaflight/betaflight-tx-lua-scripts#181]
I'm running a EWRF e708TM3 5.8G 48CH 25mW/200mW/600mW Switchable FPV Transmitter.
All the settings in the VTX page work flawlessly with the exception of the Pit Mode

**Comment by bobbfwed** [comment]
Betaflight doesn't currently support a software-driven pit mode. I'm not sure why they've included the pit mode option in Lua, and in the Modes tab in Betaflight. I'm guessing they are working on it, or are hoping it will function soon.
I think the problem is that if you rely on Betaflight to control pit mode, your VTX will still boot up at full power, then once Betaflight has booted, it can send the command to go into pit mode...it's can't just boot directly into pit mode, which is kinda the point of it. For now, we have to rely on the VTX's button.

**Comment by bonoboxita** [comment]
Clear.
Thank you.
