### ISSUE TITLE
Ability to change PID profile in script

### ISSUE THREAD

**Issue by andmiller** [betaflight/betaflight-tx-lua-scripts#230]
It would be convenient to be able to change the PID profile via the LUA script.

**Comment by kafie1980** [comment]
Here I mention about a lua script (not written by me) that probably still works on X9d size transmitters: https://github.com/betaflight/betaflight-tx-lua-scripts/issues/290#issuecomment-690254544

You should be able to change the PID profile with it and other stick based commands.

It does not work for X-Lite S probably due to screen size.
