### ISSUE TITLE
4.2 not working 

### ISSUE THREAD

**Issue by sparr88** [betaflight/betaflight-tx-lua-scripts#337]
Jumper t16 with TBS nightly build  of opentx used latest Lua script without issue on 4.1 ..  on 4.2 rc1 I get no response from Lua script and am unable to operate Lua at all

**Comment by joevo2** [comment]
bf 4.2 will need the new bf lua script v1.5.0 but not sure when is releasing

**Comment by KAJE1977** [comment]
Have you tried the nightly build of lua scripts?

**Comment by sparr88** [comment]
No please share !!

**Comment by KAJE1977** [comment]
its on the betaflight main page or try jenkins betaflight

**Comment by KAJE1977** [comment]
https://github.com/betaflight

**Comment by KAJE1977** [comment]
https://ci.betaflight.tech/view/all/

**Comment by KAJE1977** [comment]
with the new lua scripts they use a tool menu instead of the script page.

**Comment by KAJE1977** [comment]
Contributor
klutvott123 commented 22 days ago
Could be anything. Does it work as a telemetry screen?

There has been a lot of changes to the Betaflight lua scripts since 1.4.1. Would you like to try a nightly build instead https://github.com/betaflight/betaflight-tx-lua-scripts-nightlies/releases?
It's installed just like before by copying the folders to the root of the sd card. Then it can be executed from the opentx TOOLS menu. I recommend removing all old betaflight lua scripts files and folders first.

I grabbed that from the issues on here. Others are having problems also. I think the nightly build will help. alot has changed and is much nicer now.

**Comment by KAJE1977** [comment]
Just make sure you remove all the old files first so there is no conflicts.

**Comment by joevo2** [comment]
4.2 support :) great job https://github.com/betaflight/betaflight-tx-lua-scripts/releases/tag/1.5.0
