### ISSUE TITLE
bfbkgd.lua enabling makes current telemetry to 0 | TBS Crossfire | Nano Reveiver | Mamba F7

### ISSUE THREAD

**Issue by srinarayanant** [betaflight/betaflight-tx-lua-scripts#395]
Hi There,
I had enabled the https://github.com/betaflight/betaflight-tx-lua-scripts/blob/master/src/SCRIPTS/FUNCTIONS/bfbkgd.lua script in TBS Tango global configuration to get date in black box as per https://blog.dronetrest.com/blackbox-date-and-time-quick-tip/  ; It had messed up the telemetry reading of the current consumption and amp drawn shows up as ZERO ; disabling the global function in the model fixes this behavior,so look like the script is messing with TBS telemetry.

Hardware 
MAMBA STACK - F722S , F60 Pro ,TBS Crossfire Nano , TBS Tango2

**Comment by klutvott123** [comment]
That sounds very strange. bfbkgd just sends the time from TX to FC until it succeeds. After that it does absolutely nothing unless you're also using it for it's RSSI capabilities(it sends RSSI if no other source is detected). 
This is the first time I'm hearing about this issue since version 1.5.0 was released more than a year ago.
