### ISSUE TITLE
Change file name to a shorter one

### ISSUE THREAD

**Issue by nitbeat** [betaflight/betaflight-tx-lua-scripts#8]
Hello,

Why not change the filename to max 6 charechters ?
Some people forget doing that and it doesn't work properly.

Thanks :)
@raphaelcoeffic

**Comment by si618** [comment]
Just call it BF.lua

Problem solved!

**Comment by raphaelcoeffic** [comment]
@nitbeat @si618 Gents, I'm 90% with a brand new version which has the common parts between the different TXs split, so that the code is not duplicated and better organized. We will have the main scripts called after the TX-type in the repos, but the individual packages for the targets (X7, X9, Horus) will have BF.lua set as the script name.

**Comment by si618** [comment]
Sounds great, love your work Raphael!

**Comment by raphaelcoeffic** [comment]
implemented in #11

**Comment by raphaelcoeffic** [comment]
see https://github.com/betaflight/betaflight-tx-lua-scripts/releases/tag/v0.1
